"""users table

Revision ID: 144d4ad6b9e3
Revises: 
Create Date: 2019-05-23 19:45:34.754898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144d4ad6b9e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.add_column(u'user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column(u'user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'last_seen')
    op.drop_column(u'user', 'about_me')
    op.drop_table('followers')
    # ### end Alembic commands ###
